apiVersion: v1
kind: Service
metadata:
  name: hoang-capstone-service
spec:
  type: LoadBalancer
  selector:
    app: hoang-capstone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
